/**
 * Export helpers — ZIP of converted scripts + PDF audit report
 */

import type { NSAccount, ConversionResult } from "./types"

/** Download a single converted script as .js file with conversion header */
export function downloadScript(scriptName: string, code: string, changeLog?: string[]): void {
  const safeName = scriptName.replace(/[^a-z0-9_-]/gi, "_").toLowerCase()
  
  // Add conversion header with change summary
  const header = `/**
 * ═══════════════════════════════════════════════════════════════
 * 🎯 SuiteMigrate — Automated Conversion Report
 * ═══════════════════════════════════════════════════════════════
 * 
 * Original Script: ${scriptName}
 * Converted: ${new Date().toLocaleString()}
 * Tool: SuiteMigrate (suitemigrate.com)
 * 
 * WHAT CHANGED:
${changeLog && changeLog.length > 0 
    ? changeLog.map(c => ` * ✓ ${c}`).join('\n')
    : ' * • See inline comments for detailed changes'
}
 * 
 * NEXT STEPS:
 * 1. Review all lines with "// MIGRATED:" comments
 * 2. Test in NetSuite sandbox environment
 * 3. Check lines marked "// TODO: MANUAL REVIEW"
 * 4. Deploy to production after validation
 * 
 * ═══════════════════════════════════════════════════════════════
 */

`
  
  const fullCode = header + code
  const blob = new Blob([fullCode], { type: "text/javascript" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${safeName}_2.1.js`
  a.click()
  URL.revokeObjectURL(url)
}

/** Build audit report HTML and trigger download as .html file */
export function downloadAuditReport(account: NSAccount): void {
  const now = new Date().toLocaleDateString()
  const needsUpdate = account.scripts.filter((s) => s.needsMigration)
  const upToDate = account.scripts.filter((s) => !s.needsMigration)

  const rows = account.scripts
    .map(
      (s) => `
      <tr style="border-bottom:1px solid #1e3a5f">
        <td style="padding:8px 12px;color:#f1f5f9">${s.name}</td>
        <td style="padding:8px 12px;color:#94a3b8">${s.scriptType}</td>
        <td style="padding:8px 12px;color:#94a3b8">SS ${s.apiVersion}</td>
        <td style="padding:8px 12px">
          <span style="
            background:${s.riskLevel === "HIGH" ? "#7f1d1d" : s.riskLevel === "MEDIUM" ? "#78350f" : "#14532d"};
            color:${s.riskLevel === "HIGH" ? "#fca5a5" : s.riskLevel === "MEDIUM" ? "#fcd34d" : "#86efac"};
            padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600
          ">${s.riskLevel}</span>
        </td>
        <td style="padding:8px 12px;color:${s.needsMigration ? "#fca5a5" : "#86efac"}">
          ${s.needsMigration ? "Needs Migration" : "✓ Up to date"}
        </td>
      </tr>`
    )
    .join("")

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SuiteMigrate Audit Report — ${account.accountName}</title>
  <style>
    body { font-family: -apple-system, sans-serif; background: #050d1a; color: #f1f5f9; padding: 32px; }
    h1 { color: #10b981; margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 24px; }
    th { text-align: left; padding: 10px 12px; background: #0a1628; color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
  </style>
</head>
<body>
  <h1>SuiteMigrate Audit Report</h1>
  <p style="color:#64748b">Account: <strong style="color:#f1f5f9">${account.accountName}</strong> &nbsp;|&nbsp; Generated: ${now}</p>

  <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0">
    <div style="background:#0a1628;border:1px solid #1e3a5f;border-radius:8px;padding:16px">
      <div style="font-size:28px;font-weight:700;color:#f1f5f9">${account.scripts.length}</div>
      <div style="color:#64748b;font-size:13px">Total Scripts</div>
    </div>
    <div style="background:#0a1628;border:1px solid #1e3a5f;border-radius:8px;padding:16px">
      <div style="font-size:28px;font-weight:700;color:#fbbf24">${needsUpdate.length}</div>
      <div style="color:#64748b;font-size:13px">Need Migration</div>
    </div>
    <div style="background:#0a1628;border:1px solid #1e3a5f;border-radius:8px;padding:16px">
      <div style="font-size:28px;font-weight:700;color:#10b981">${upToDate.length}</div>
      <div style="color:#64748b;font-size:13px">Already on 2.1</div>
    </div>
  </div>

  <h2 style="font-size:16px;color:#94a3b8;margin-bottom:8px">Scripts</h2>
  <table>
    <thead>
      <tr><th>Script Name</th><th>Type</th><th>Version</th><th>Risk</th><th>Status</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <p style="margin-top:32px;color:#374151;font-size:12px">
    Generated by SuiteMigrate — suitemigrate.com
  </p>
</body>
</html>`

  const blob = new Blob([html], { type: "text/html" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `suitemigrate_audit_${account.accountId}_${Date.now()}.html`
  a.click()
  URL.revokeObjectURL(url)
}

/** Export all conversions as a bundle of JS files (simple multi-download) */
export function downloadAllConversions(conversions: ConversionResult[]): void {
  if (!conversions.length) return
  conversions.forEach((c) => {
    setTimeout(() => downloadScript(c.scriptName, c.convertedCode), 100)
  })
}
